package com.example.demo.enums;

public enum CategoryTypes {
    ELECTRONICS,
    FASHION,
    HOME_AND_FURNITURE,
    BEAUTY_AND_PERSONAL_CARE,
    SPORTS_AND_OUTDOORS,
    HEALTH_AND_WELLNESS,
    TOYS_AND_BABY,
    BOOKS_AND_STATIONERY,
    GROCERIES_AND_GOURMET,
    AUTOMOTIVE,
    PETS,
    ARTS_AND_CRAFTS_AND_HOBBIES,
    OFFICE_SUPPLIES,
    GIFTS_AND_OCCASIONS,
    FOOD_AND_BEVERAGES,
    DIGITAL_PRODUCTS,
    TRAVEL_AND_LUGGAGE,
    CRAFTS_AND_HANDMADE,
    LUXURY,
    INDUSTRIAL_AND_SCIENTIFIC;
}
