package com.example.demo.enums;

public enum SubCategory {
  MOBILE_PHONES,
  LAPTOPS,
  HEADPHONES, 
  CAMERAS, 
  TELEVISIONS,

  MEN_CLOTHING, WOMEN_CLOTHING, FOOTWEAR, ACCESSORIES, JEWELRY,

  LIVING_ROOM, KITCHEN, BATHROOM, BEDROOM, OFFICE_FURNITURE,

  SKIN_CARE, HAIR_CARE, MAKEUP, FRAGRANCES, PERSONAL_GROOMING,

  FITNESS, OUTDOOR_GEAR, SPORTS_EQUIPMENT, CYCLING, CAMPING,

  SUPPLEMENTS, WELLNESS_PRODUCTS, MEDICAL_SUPPLIES, FITNESS_TRACKERS,

  BABY_CARE, TOYS, DIAPERS, BABY_FURNITURE,

  FICTION, NON_FICTION, ACADEMIC_BOOKS, ART_SUPPLIES, OFFICE_SUPPLIES,

  FRESH_FOOD, SNACKS, ORGANIC_FOOD, GOURMET_GIFTS,

  CAR_ACCESSORIES, MOTORBIKES, AUTO_PARTS, CAR_CARE_PRODUCTS,

  PET_FOOD, PET_CARE, PET_ACCESSORIES, PET_FURNITURE,

  PAINTING, KNITTING, SCULPTING, CRAFT_TOOLS,

  PAPER_PRODUCTS, STATIONERY, PRINTERS, OFFICE_EQUIPMENT,

  GIFTS, PARTY_SUPPLIES, HOLIDAY_DECOR,

  BEVERAGES, GOURMET_FOOD, 

  EBOOKS, ONLINE_COURSES, SOFTWARE, MUSIC, VIDEO_GAMES,

  SUITCASES, BACKPACKS, TRAVEL_ACCESSORIES, LUGGAGE_CARE,

  HANDMADE_JEWELRY, HANDCRAFTED_FURNITURE, ARTWORK, HOMEMADE_CANDLES,

  HIGH_END_FASHION, LUXURY_WATCHES, PREMIUM_FURNITURE, ART,

  INDUSTRIAL_EQUIPMENT, SCIENTIFIC_TOOLS;
}

